language: node_js
node_js:
  - "10"
env:
  - CI=true
cache:
  yarn: true
  directories:
    - node_modules
stages:
  - test
  - build
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: "test"
      name: "Format check"
      script: yarn format:ci
    - stage: "test"
      name: "Unit test"
      script:
        - yarn test:prod
        - bash <(curl -s https://codecov.io/bash) -cF javascript

    - stage: "build"
      name: "Build project"
      script: yarn build
    - stage: "build"
      name: "Build docz"
      script: yarn build:doc

    - stage: "deploy"
      name: "Deploy docs"
      script: yarn build:doc && yarn run deploy-docs
    - stage: "deploy"
      name: "Deploy project"
      script: yarn run semantic-release
